# Generated by Django 4.1.7 on 2023-03-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='sotto_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.sottoserie', verbose_name='Tipo Pass'),
        ),
    ]
