# Generated by Django 4.1.7 on 2023-03-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_alter_badge_sotto_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellostampabadge',
            name='font_size_codice',
            field=models.IntegerField(blank=True, help_text='dimensione del font utilizzato per il codice, se vuoto verrà utilizzato 14', null=True),
        ),
    ]
