# Generated by Django 4.1.7 on 2023-03-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0003_modellostampabadge_font_size_codice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modellostampabadge',
            name='font_size_codice',
        ),
    ]
