# Generated by Django 4.1.7 on 2023-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0004_remove_modellostampabadge_font_size_codice'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellostampabadge',
            name='font_size_codice',
            field=models.IntegerField(blank=True, help_text='dimensione del font utilizzato per il codice, se vuoto verrà utilizzato 14', null=True),
        ),
    ]
