# Generated by Django 4.1.7 on 2023-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0005_modellostampabadge_font_size_codice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatomodellobadge',
            name='font_type',
            field=models.CharField(blank=True, help_text='Font type, se vuoto verrà utilizzato il font default Courier, testati Times-Roman e Helvetica', max_length=100, null=True),
        ),
    ]
