# Generated by Django 4.1.7 on 2023-03-13 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badge', '0006_alter_metadatomodellobadge_font_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('CHECKER', 'Verificatore'), ('GESTORE', 'Gestore')], default='CHECKER', max_length=20)),
                ('data_inizio_validita', models.DateField(help_text='data inizio validità')),
                ('data_fine_validita', models.DateField(blank=True, help_text='data fine validità', null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.serie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ruolo su serie per utente',
                'verbose_name_plural': 'ruoli su serie per utente',
            },
        ),
    ]
