# Generated by Django 4.1.7 on 2023-03-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badge', '0008_alter_userseries_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseries',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
