# Generated by Django 4.1.7 on 2023-03-13 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badge', '0009_alter_userseries_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userseries',
            unique_together={('user', 'serie')},
        ),
    ]
