# Generated by Django 4.1.7 on 2023-03-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0010_alter_userseries_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatomodellobadge',
            name='height',
            field=models.IntegerField(blank=True, default=15, help_text="altezza metadato immagine in mm, se null verrà presa la larghezza dell'immagine", null=True),
        ),
        migrations.AddField(
            model_name='metadatomodellobadge',
            name='width',
            field=models.IntegerField(blank=True, default=15, help_text="larghezza metadato immagine in mm, se null verrà presa la larghezza dell'immagine", null=True),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='border',
            field=models.IntegerField(default=3, help_text="bordo del qrcode in unità di larghezza del singolo box, 'spec says border should be at least four boxes wide' (test effettuato con valore 3) "),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='box_size',
            field=models.IntegerField(default=2, help_text='dimensione del singolo box in pixel del QRCODE, (test effettuato con valore 2)'),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='font_size_codice',
            field=models.IntegerField(blank=True, default=18, help_text='dimensione del font utilizzato per il codice, se vuoto verrà utilizzato 18 con font di tipo Courier', null=True),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='height',
            field=models.IntegerField(blank=True, default=148, help_text='altezza Pass in mm (148 per A6)', null=True),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='version',
            field=models.IntegerField(default=7, help_text='version del QRCODE, default a 7 con ECC level al massimo arriva fino a 93 caratteri, attualmente url codificato è di 85 caratteri. Dettagli tecnici https://www.qrcode.com/en/about/version.html'),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='width',
            field=models.IntegerField(blank=True, default=105, help_text='larghezza Pass in mm (105 per A6)', null=True),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='x_print_codice',
            field=models.IntegerField(blank=True, default=35, help_text='coordinata bottom left origin x in mm dove stampare il codice Pass', null=True),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='x_px_qr',
            field=models.IntegerField(default=34, help_text='coordinata bottom left origin per il print del QRCODE in mm', verbose_name='x print QR (mm)'),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='y_print_codice',
            field=models.IntegerField(blank=True, default=98, help_text='coordinata bottom left origin y in mm dove stampare il codice Pass', null=True),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='y_px_qr',
            field=models.IntegerField(default=33, help_text='coordinata bottom left origin per il print del QRCODE in mm', verbose_name='y print QR (mm)'),
        ),
    ]
