# Generated by Django 4.1.7 on 2023-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0011_metadatomodellobadge_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatomodellobadge',
            name='tipo_pvc',
            field=models.CharField(choices=[('GENERICO', 'Generico'), ('COMUNE', 'Personale comune'), ('PARTICOLARE', 'Personale particolare')], default='GENERICO', max_length=12, verbose_name='Tipologia dato privacy'),
        ),
        migrations.AlterField(
            model_name='metadatomodellobadge',
            name='tipo_metadato',
            field=models.CharField(choices=[('STRING', 'Stringa'), ('TEXT', 'Testo'), ('DATE', 'Data'), ('FILE', 'File'), ('IMAGE', 'Image'), ('HTML', 'Testo HTML')], default='STRING', max_length=6),
        ),
    ]
