# Generated by Django 4.1.7 on 2023-03-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0014_alter_modellostampabadge_x_print_codice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatomodellobadge',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, help_text="altezza metadato immagine in mm, se null verrà presa la larghezza dell'immagine", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='metadatomodellobadge',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, help_text="larghezza metadato immagine in mm, se null verrà presa la larghezza dell'immagine", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='metadatomodellobadge',
            name='x_print',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='coordinata bottom left origin in mm dove stampare il campo', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='metadatomodellobadge',
            name='y_print',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='coordinata bottom left origin in mm dove stampare il campo', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=148, help_text='altezza Pass in mm (148 per A6)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=105, help_text='larghezza Pass in mm (105 per A6)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='x_px_qr',
            field=models.DecimalField(decimal_places=2, default=34, help_text='coordinata bottom left origin per il print del QRCODE in mm', max_digits=5, verbose_name='x print QR (mm)'),
        ),
        migrations.AlterField(
            model_name='modellostampabadge',
            name='y_px_qr',
            field=models.DecimalField(decimal_places=2, default=33, help_text='coordinata bottom left origin per il print del QRCODE in mm', max_digits=5, verbose_name='y print QR (mm)'),
        ),
    ]
