# Generated by Django 4.1.7 on 2023-05-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0015_alter_metadatomodellobadge_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='key', max_length=255)),
                ('data_inizio_validita', models.DateField(help_text='data inizio validità')),
                ('data_fine_validita', models.DateField(blank=True, help_text='data fine validità', null=True)),
                ('sotto_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.sottoserie')),
            ],
            options={
                'unique_together': {('sotto_serie', 'key')},
            },
        ),
    ]
