# Generated by Django 4.1.7 on 2024-12-19 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VCard',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organizzazione', models.CharField(default='Comune di Bari', max_length=100)),
                ('titolo', models.CharField(blank=True, max_length=10, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('profilo', models.CharField(max_length=100)),
                ('ufficio', models.CharField(max_length=150)),
                ('indirizzo_ufficio', models.CharField(max_length=255)),
                ('telefono_fisso', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_cellulare', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('vcf_file', models.CharField(max_length=100)),
            ],
        ),
    ]

