# Generated by Django 4.1.7 on 2024-12-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcard',
            name='vcf_file',
            field=models.CharField(default='pippo.vcf', max_length=100),
            preserve_default=False,
        ),
    ]

