# Generated by Django 4.1.7 on 2024-12-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcard',
            name='vcf_file',
        ),
    ]
