# Generated by Django 4.1.7 on 2024-12-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0002_vcard_vcf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcard',
            name='user',
        ),
    ]

