# Generated by Django 4.1.7 on 2024-12-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0003_remove_vcard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcard',
            name='vcf_file',
        ),
        migrations.AddField(
            model_name='vcard',
            name='effetto_neve',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
