# Generated by Django 4.1.7 on 2024-12-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0004_remove_vcard_vcf_file_vcard_effetto_neve'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcard',
            name='effetto_epifania',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
